INSERT INTO breed(name) VALUES('Affenpinscher');
INSERT INTO breed(name) VALUES('Afghan Hound');
INSERT INTO breed(name) VALUES('Airedale Terrier');
INSERT INTO breed(name) VALUES('Akita');
INSERT INTO breed(name) VALUES('Alaskan Malamute');
INSERT INTO breed(name) VALUES('American English Coonhound');
INSERT INTO breed(name) VALUES('American Eskimo Dog');
INSERT INTO breed(name) VALUES('American Foxhound');
INSERT INTO breed(name) VALUES('American Staffordshire Terrier');
INSERT INTO breed(name) VALUES('American Water Spaniel');
INSERT INTO breed(name) VALUES('Anatolian Shepherd Dog');
INSERT INTO breed(name) VALUES('Australian Cattle Dog');
INSERT INTO breed(name) VALUES('Australian Shepherd');
INSERT INTO breed(name) VALUES('Australian Terrier');
INSERT INTO breed(name) VALUES('Basenji');
INSERT INTO breed(name) VALUES('Basset Hound');
INSERT INTO breed(name) VALUES('Beagle');
INSERT INTO breed(name) VALUES('Bearded Collie');
INSERT INTO breed(name) VALUES('Beauceron');
INSERT INTO breed(name) VALUES('Bedlington Terrier');
INSERT INTO breed(name) VALUES('Belgian Malinois');
INSERT INTO breed(name) VALUES('Belgian Sheepdog');
INSERT INTO breed(name) VALUES('Belgian Tervuren');
INSERT INTO breed(name) VALUES('Bernese Mountain Dog');
INSERT INTO breed(name) VALUES('Bichon Frise');
INSERT INTO breed(name) VALUES('Black and Tan Coonhound');
INSERT INTO breed(name) VALUES('Black Russian Terrier');
INSERT INTO breed(name) VALUES('Bloodhound');
INSERT INTO breed(name) VALUES('Bluetick Coonhound');
INSERT INTO breed(name) VALUES('Border Collie');
INSERT INTO breed(name) VALUES('Border Terrier');
INSERT INTO breed(name) VALUES('Borzoi');
INSERT INTO breed(name) VALUES('Boston Terrier');
INSERT INTO breed(name) VALUES('Bouvier des Flandres');
INSERT INTO breed(name) VALUES('Boxer');
INSERT INTO breed(name) VALUES('Boykin Spaniel');
INSERT INTO breed(name) VALUES('Briard');
INSERT INTO breed(name) VALUES('Brittany');
INSERT INTO breed(name) VALUES('Brussels Griffon');
INSERT INTO breed(name) VALUES('Bull Terrier');
INSERT INTO breed(name) VALUES('Bulldog');
INSERT INTO breed(name) VALUES('Bullmastiff');
INSERT INTO breed(name) VALUES('Cairn Terrier');
INSERT INTO breed(name) VALUES('Canaan Dog');
INSERT INTO breed(name) VALUES('Cane Corso');
INSERT INTO breed(name) VALUES('Cardigan Welsh Corgi');
INSERT INTO breed(name) VALUES('Cavalier King Charles Spaniel');
INSERT INTO breed(name) VALUES('Cesky Terrier');
INSERT INTO breed(name) VALUES('Chesapeake Bay Retriever');
INSERT INTO breed(name) VALUES('Chihuahua');
INSERT INTO breed(name) VALUES('Chinese Crested');
INSERT INTO breed(name) VALUES('Chinese Shar-Pei');
INSERT INTO breed(name) VALUES('Chow Chow');
INSERT INTO breed(name) VALUES('Clumber Spaniel');
INSERT INTO breed(name) VALUES('Cocker Spaniel');
INSERT INTO breed(name) VALUES('Collie');
INSERT INTO breed(name) VALUES('Curly-Coated Retriever');
INSERT INTO breed(name) VALUES('Dachshund');
INSERT INTO breed(name) VALUES('Dalmatian');
INSERT INTO breed(name) VALUES('Dandie Dinmont Terrier');
INSERT INTO breed(name) VALUES('Doberman Pinscher');
INSERT INTO breed(name) VALUES('Dogue de Bordeaux');
INSERT INTO breed(name) VALUES('English Cocker Spaniel');
INSERT INTO breed(name) VALUES('English Foxhound');
INSERT INTO breed(name) VALUES('English Setter');
INSERT INTO breed(name) VALUES('English Springer Spaniel');
INSERT INTO breed(name) VALUES('English Toy Spaniel');
INSERT INTO breed(name) VALUES('Entlebucher Mountain Dog');
INSERT INTO breed(name) VALUES('Field Spaniel');
INSERT INTO breed(name) VALUES('Finnish Lapphund');
INSERT INTO breed(name) VALUES('Finnish Spitz');
INSERT INTO breed(name) VALUES('Flat-Coated Retriever');
INSERT INTO breed(name) VALUES('French Bulldog');
INSERT INTO breed(name) VALUES('German Pinscher');
INSERT INTO breed(name) VALUES('German Shepherd Dog');
INSERT INTO breed(name) VALUES('German Shorthaired Pointer');
INSERT INTO breed(name) VALUES('German Wirehaired Pointer');
INSERT INTO breed(name) VALUES('Giant Schnauzer');
INSERT INTO breed(name) VALUES('Glen of Imaal Terrier');
INSERT INTO breed(name) VALUES('Golden Retriever');
INSERT INTO breed(name) VALUES('Gordon Setter');
INSERT INTO breed(name) VALUES('Great Dane');
INSERT INTO breed(name) VALUES('Great Pyrenees');
INSERT INTO breed(name) VALUES('Greater Swiss Mountain Dog');
INSERT INTO breed(name) VALUES('Greyhound');
INSERT INTO breed(name) VALUES('Harrier');
INSERT INTO breed(name) VALUES('Havanese');
INSERT INTO breed(name) VALUES('Ibizan Hound');
INSERT INTO breed(name) VALUES('Icelandic Sheepdog');
INSERT INTO breed(name) VALUES('Irish Red and White Setter');
INSERT INTO breed(name) VALUES('Irish Setter');
INSERT INTO breed(name) VALUES('Irish Terrier');
INSERT INTO breed(name) VALUES('Irish Water Spaniel');
INSERT INTO breed(name) VALUES('Irish Wolfhound');
INSERT INTO breed(name) VALUES('Italian Greyhound');
INSERT INTO breed(name) VALUES('Japanese Chin');
INSERT INTO breed(name) VALUES('Keeshond');
INSERT INTO breed(name) VALUES('Kerry Blue Terrier');
INSERT INTO breed(name) VALUES('Komondor');
INSERT INTO breed(name) VALUES('Kuvasz');
INSERT INTO breed(name) VALUES('Labrador Retriever');
INSERT INTO breed(name) VALUES('Lakeland Terrier');
INSERT INTO breed(name) VALUES('Leonberger');
INSERT INTO breed(name) VALUES('Lhasa Apso');
INSERT INTO breed(name) VALUES('Löwchen');
INSERT INTO breed(name) VALUES('Maltese');
INSERT INTO breed(name) VALUES('Manchester Terrier');
INSERT INTO breed(name) VALUES('Mastiff');
INSERT INTO breed(name) VALUES('Miniature Bull Terrier');
INSERT INTO breed(name) VALUES('Miniature Pinscher');
INSERT INTO breed(name) VALUES('Miniature Schnauzer');
INSERT INTO breed(name) VALUES('Neapolitan Mastiff');
INSERT INTO breed(name) VALUES('Newfoundland');
INSERT INTO breed(name) VALUES('Norfolk Terrier');
INSERT INTO breed(name) VALUES('Norwegian Buhund');
INSERT INTO breed(name) VALUES('Norwegian Elkhound');
INSERT INTO breed(name) VALUES('Norwegian Lundehund');
INSERT INTO breed(name) VALUES('Norwich Terrier');
INSERT INTO breed(name) VALUES('Nova Scotia Duck Tolling Retriever');
INSERT INTO breed(name) VALUES('Old English Sheepdog');
INSERT INTO breed(name) VALUES('Otterhound');
INSERT INTO breed(name) VALUES('Papillon');
INSERT INTO breed(name) VALUES('Parson Russell Terrier');
INSERT INTO breed(name) VALUES('Pekingese');
INSERT INTO breed(name) VALUES('Pembroke Welsh Corgi');
INSERT INTO breed(name) VALUES('Petit Basset Griffon Vendéen');
INSERT INTO breed(name) VALUES('Pharaoh Hound');
INSERT INTO breed(name) VALUES('Plott');
INSERT INTO breed(name) VALUES('Pointer');
INSERT INTO breed(name) VALUES('Polish Lowland Sheepdog');
INSERT INTO breed(name) VALUES('Pomeranian');
INSERT INTO breed(name) VALUES('Poodle');
INSERT INTO breed(name) VALUES('Portuguese Water Dog');
INSERT INTO breed(name) VALUES('Pug');
INSERT INTO breed(name) VALUES('Puli');
INSERT INTO breed(name) VALUES('Pyrenean Shepherd');
INSERT INTO breed(name) VALUES('Redbone Coonhound');
INSERT INTO breed(name) VALUES('Rhodesian Ridgeback');
INSERT INTO breed(name) VALUES('Rottweiler');
INSERT INTO breed(name) VALUES('Saint Bernard');
INSERT INTO breed(name) VALUES('Saluki');
INSERT INTO breed(name) VALUES('Samoyed');
INSERT INTO breed(name) VALUES('Schipperke');
INSERT INTO breed(name) VALUES('Scottish Deerhound');
INSERT INTO breed(name) VALUES('Scottish Terrier');
INSERT INTO breed(name) VALUES('Sealyham Terrier');
INSERT INTO breed(name) VALUES('Shetland Sheepdog');
INSERT INTO breed(name) VALUES('Shiba Inu');
INSERT INTO breed(name) VALUES('Shih Tzu');
INSERT INTO breed(name) VALUES('Siberian Husky');
INSERT INTO breed(name) VALUES('Silky Terrier');
INSERT INTO breed(name) VALUES('Skye Terrier');
INSERT INTO breed(name) VALUES('Smooth Fox Terrier');
INSERT INTO breed(name) VALUES('Soft Coated Wheaten Terrier');
INSERT INTO breed(name) VALUES('Spinone Italiano');
INSERT INTO breed(name) VALUES('Staffordshire Bull Terrier');
INSERT INTO breed(name) VALUES('Standard Schnauzer');
INSERT INTO breed(name) VALUES('Sussex Spaniel');
INSERT INTO breed(name) VALUES('Swedish Vallhund');
INSERT INTO breed(name) VALUES('Tibetan Mastiff');
INSERT INTO breed(name) VALUES('Tibetan Spaniel');
INSERT INTO breed(name) VALUES('Tibetan Terrier');
INSERT INTO breed(name) VALUES('Toy Fox Terrier');
INSERT INTO breed(name) VALUES('Vizsla');
INSERT INTO breed(name) VALUES('Weimaraner');
INSERT INTO breed(name) VALUES('Welsh Springer Spaniel');
INSERT INTO breed(name) VALUES('Welsh Terrier');
INSERT INTO breed(name) VALUES('West Highland White Terrier');
INSERT INTO breed(name) VALUES('Whippet');
INSERT INTO breed(name) VALUES('Wire Fox Terrier');
INSERT INTO breed(name) VALUES('Wirehaired Pointing Griffon');
INSERT INTO breed(name) VALUES('Xoloitzcuintli');
INSERT INTO breed(name) VALUES('Yorkshire Terrier');
